### ISSUE TITLE
Archiving Link on unversioned Owner does not delete from Live table

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#158]
Link is versioned by default.

If you put a LinkField on an unversioned owner dataobject editing via a gridfield, saving the owner will save & publish the Link.  

However when clicking the LinkField "Archive" button the Link record in only deleted from the draft LinkField_Link table and not the LinkField_Link_Live table;

**Comment by GuySartorelli** [comment]
Is this bug specific to this module? Or does the same happen when archiving a versioned record in a gridfield as well, when the gridfield is on an unversioned model?

**Comment by emteknetnz** [comment]
No 'regular' dataobjects edited via gridfield behave differently
- Saving the unversioned parent dataobject will not auto-publish a child versioned dataobject, instead it will only save the the child
- Inline archiving the versioned child dataobject via the gridfield will remove the record from both the draft and live tables

**Comment by GuySartorelli** [comment]
> Saving the unversioned parent dataobject will not auto-publish a child versioned dataobject, instead it will only save the the child

Did you check that with the `$owns` configuration applied? The child _should_ be published if `$owns` configuration dictates that the unversioned parent owns the versioned child.

> Inline archiving the versioned child dataobject via the gridfield will remove the record from both the draft and live tables

Ultimately this is the part that matters, so if that works fine in gridfield then we can safely say this bug is unique to this module (or at least uniquely _exhibited_ by this module - it could still be a bug in versioned somewhere that gridfield just doesn't trigger for some reason).

**Comment by emteknetnz** [comment]
Cannot replicate, quite possibly did not have $cascade_deletes or $owns
