### ISSUE TITLE
CMS 5.2.0-beta1. Regression test: Versioned label should be on both sorted links

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-linkfield#254]
## Description
Executed on: SC PHP 8.3 Chrome Sink

When sorting links using Drag and Drop, the version label does not always appear on the first link in the list. This behavior is not permanent and can work correctly from case to case.

### Steps to reproduce issue:
- I have at least two links in MultiLinkField;
- I move first link down using Drag and Drop and place it after second link;
- I see that my current first link doesn't have label "Modified";
- I see that my current second link has label "Modified";

My expectation that both links should be marked as "Modified".

## Acceptance criteria
- Newly created links in a Link List are added to the end of the list and have the matching sort value assigned to them.
- Cuccumber studio scenario for sorting links have consistent and repeatable steps.

**Comment by GuySartorelli** [comment]
Check in the DB and see if the sort value has actually changed for both links.
If `Sort` hasn't changed for one of the links, then the link hasn't actually been modified.

**Comment by sabina-talipova** [comment]
This happens for two identical scenarios in a row. For example, I expect that first Link should have Sort = 1 and second Link should have Sort = 2. When we change their position in the list(reorder two first links), I expect that first Link will have Sort = 2  and second Link has Sort = 1. 
Should we expect to having a badge in LinkField in this case?
In any case something goes wrong, since sometimes we see badge, sometimes not.

**Comment by maxime-rainville** [comment]
To the extent that `modified` label reflects the underlying state of the object, I'm not overly fuss about how the sorting works.

I'm not too concern about the sorting algo works under the hood.

Let's say you have item 1, 2, 3 and 4. You change item 2 to come first:
- If only item 2 and 1 are marked as modified, that's fine.
- If the sorting on all item is updated because they all have a refreshed sorting order and they all come up as "modified, that's fine too.

**Comment by maxime-rainville** [comment]
I suspect that part of the problem is that new Link, seem to default to having a `Sort` of `1`.

## Repo steps
- Start with a list of 4 links.
- Sort them around so they all have an order set to them.
- Publish your changes
- Create a brand new link.
- New link is added at the end of the list
- Refresh the page

Expected results: New link is at the end of the list.
Actual results: New link is in the second spot.

If you look at the DB, you'll find that the new link has a Sort of 1. It's showing up in the second spot because one other link will have a Sort of 1.


[linkfield-2024-03-18_17.07.39.webm](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/4188fe0e-1ed6-48bb-9c80-d06fbcbfe495)

**Comment by sabina-talipova** [comment]
I assume that this issue can be solved as part of this issue https://github.com/silverstripe/silverstripe-linkfield/issues/258

**Comment by sabina-talipova** [comment]
Issue was solved by https://github.com/silverstripe/silverstripe-linkfield/pull/262.
Close ticket.
