### ISSUE TITLE
Migration tasks missing from 4.0.0-rc1

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-linkfield#272]
### Module version(s) affected

4.0.0-rc1

### Description

When trying to follow the migration guide for GorrieCoe LinkField, there are docs referencing a task that's missing.

`composer require silverstripe/linkfield:^4`

https://github.com/silverstripe/silverstripe-linkfield/tree/4.0.0-rc1/src/Tasks -> 404

### How to reproduce

`vendor/bin/sake dev/tasks/linkfield-tov4-migration-task`

### Possible Solution

recommit with src/Tasks folder (present in 4 branch and beta1 tag)

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by elliot-sawyer** [comment]
Just spotted `@deprecated 4.0.0 Will be removed without equivalent functionality.`, which seems a bit odd to me.  Why would you do all the work to offer a migration path, with excellent documentation, to this new module just to remove it in v4?

**Comment by GuySartorelli** [comment]
The migration tasks and docs are targetting the Silverstripe CMS 5.3 release (i.e. the silverstripe/linkfield 4.1.0 release) - they unfortunately didn't make it in time for the 5.2 (linkfield 4.0) release and depend on some ORM API changes that aren't going to be available in Silverstripe CMS 5.2.

They tasks are deprecated because they'll be removed in a future major release. They're not being removed in v4, they're being added in v4 and removed in a future major release.
