### ISSUE TITLE
Module standardisation

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#95]
## Story
As a dev team, we want the module to be in a good state for development.

## Acceptance criteria
- [x] Linkfield is added to Rihno
- [x] A next major branch is created and follows our conventions
- [x] Module is set up to run our standard CI
- [ ] Module is tracked in transifex
- [ ] Module is added to the sink
- [x] Module is constrained to CMS 5

## PRs
- https://github.com/silverstripe/silverstripe-linkfield/pull/100
- https://github.com/silverstripe/recipe-kitchen-sink/pull/48
- https://github.com/silverstripe/silverstripe-linkfield/pull/93

**Comment by emteknetnz** [comment]
This card is mostly done

> Linkfield is added to Rhino

I've updated rhino, linkfield is now showing

> A next major branch is created and follows our conventions

I've created a new `4` branch from the old `3` branch and added the standard branch protection rules.  We'll hold off making a `4.0` branch until we're ready to tag stable so so that we don't need to worry about merge-up overhead.

I've changed the default branch to `4` so that new PR's target that so we don't accidentally target the wrong branch. Note the old major `3` never got out of beta so I don't think it's incorrect to just change the default branch now.

> Module is set up to run our standard CI

I've got a PR open for this https://github.com/silverstripe/silverstripe-linkfield/pull/93

> Module is tracked in transifex

I've created a new project in transifex `silverstripe-linkfield` and copied settings for the existing `silverstripe-versioned` - though we'll need to actually push some translation up before it's fully ready.  There are no existing translations in linkfield though we'll inevitably add some

> Module is added to the sink

PR https://github.com/silverstripe/recipe-kitchen-sink/pull/48

> Module is constrained to CMS 5

The `4` branch has a composer requirement for silverstripe/cms ^5

**Comment by GuySartorelli** [comment]
Can we please not action cards like this without refining them? This module should not be in rhino or kitchen sink imo.

**Comment by maxime-rainville** [comment]
Some of these ACs have already been actioned. There's some point to sort out about how and we iterate and promote linkfield once we actively start working on it.

**Comment by GuySartorelli** [comment]
Outstanding PRs and acceptance criteria have been moved to https://github.com/silverstripe/silverstripe-linkfield/issues/78
Closing as duplicate
