### ISSUE TITLE
LinkField is accessible

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#99]
## Story
As visually impaired content author, I want to be able to manage Links.

## Some things to watch out for
- should be able to tab through links and press enter to open the modal, even in read-only
- opening the modal should give focus to the first field in the modal automatically
- if closing or submitting the modal using the keyboard, focus should be returned to the button which would open the modal for that link (or to the "add link" button for new link modal)
- Should be able to submit modal using the enter key when focus is on any text field
- Should be able to reorder links with the keyboard.
- Aria label should be present whenever an image/icon is used instead of text.

## Acceptance criteria
- Accessibility issues with LinkField are identified.
- Simple issues are addressed.
- Complex issues are spun up as separate card.

## Exception
- In some cases the LinkField maybe reusing other CMS UI elements that are not accessible (e.g. File Upload modal). Fixing those other elements is beyond the scope of this card.

## Note
- Since this is a one of the first time we do a proper accessibility review, we should take learning from this card into a retro topic.

## New issues created
- https://github.com/silverstripe/silverstripe-linkfield/issues/205

## PRs
- https://github.com/silverstripe/silverstripe-linkfield/pull/200

**Comment by maxime-rainville** [comment]
Cassie said this should be a high priority.

**Comment by emteknetnz** [comment]
> opening the modal should give focus to the first field in the modal automatically

This one is too hard for now.  Since the modal is not part of linkfield it should be enhanced in admin instead of doing something hackish in linkfield to get it to focus on the first.

In order to do this properly we'd need to create a ref via `useRef()` in FormBuilder for each field that's created, and pass that into the create form field component via an innerRef prop, and in EVERY one of react components add an innerRef prop and then put that ref on the relevant `<input>` or whatever.   We'd then have a new prop in form builder focusOnFirstField=false which can be set to true, which we'd do if opening the form builder modal via keyboard, and then formbuilder with go someRef.current.focus() on open.  This would be a signficant piece of work.

While this is nice to have, in practice all it does is save 2x tab presses to focus the first input

**Comment by emteknetnz** [comment]
> Accessibility issues with LinkField are identified.

Going from https://govtnz.github.io/web-a11y-guidance/

**Accessible UX best practices:**
- Colour and contract - Out of scope for this card - broader issue with CMS that should be dealt with in a CMS redesign
- Designing documents for print - Not applicable for the CMS
- Keyboard accessibility - Linked PR implements - I think LinkField should now be compliant with everything there?
- Language of content - Out of scope for this card - broader issue with CMS, though I'm honestly not sure if it's an issue right now since we already have translatable support

Linked PR implements keyboard nav and I honestly don't know what else to look for accessibility issues with linkfield

> Complex issues are spun up as separate card.

To meet the AC's I could spin up a new card to look at accessibility of the CMS in terms of colors / contrast / font sizes etc, though I'm not sure what value there is of that in isolation - I'd expect that sort of card would be created as part of a broader CMS design refresh epic

**Comment by GuySartorelli** [comment]
Might make sense to open a card to add behat tests for whatever scenarios you couldn't cover in jest

**Comment by emteknetnz** [comment]
Have creating a new issue to use behat to test keyboard sorting https://github.com/silverstripe/silverstripe-linkfield/issues/205

**Comment by sabina-talipova** [comment]
Task is completed. PR's merged.
